version: '3.8'

services:
  web:
    build: .
    container_name: django_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_NAME=multivendor
      - DATABASE_USER=yourusername
      - DATABASE_PASSWORD=yourpassword
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: multivendor
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
